const ACTIONS = {
  ALERT: 'ALERT',
  ALERT_CLOSE: 'ALERT_CLOSE',
  USER_EMAIL_PASS: 'USER_EMAIL_PASS',
  HEIGHT_WEIGHT: 'HEIGHT_WEIGHT',
  USER_AGE: 'USER_AGE',
  USER_GENDER: 'USER_GENDER',
  USER_ETHNICITY: 'USER_ETHNICITY',
  USER_MARITAL_STATUS: 'USER_MARITAL_STATUS',
};

export default ACTIONS;
